version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  test_node_api:
    depends_on:
      - mysql
    build: .
    container_name: test_node_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      # This is for development only and should be removed in production environment to avoid exposing the code
      # This allow us to make changes to the code and see the changes without having to rebuild the image
      - ./:/usr/src/app

volumes:
  db:
